### PR TITLE
symlinks support

### PR DESCRIPTION
**Pull request by fabriziofortino**
If the template repo contains symbolic links g8 does not recognise them and the content gets duplicated.

The PR handles this creating symbolic links when detected. Unfortunately this works for local templates only at the moment. To support remote repos as well we should upgrade jgit (symlinks support has been added in a later version https://bugs.eclipse.org/bugs/show_bug.cgi?id=354367) but I am not sure we can do this. It would be awesome to have this feature. Any idea?

### CODE REVIEW

**Comment by fabriziofortino** [comment]
I have upgraded `jgit` with the same version used in sbt-git [master branch] https://github.com/sbt/sbt-git/blob/358e169ba5d679b45863c0f59ca930fc5c93a01a/build.sbt

Symbolic links work well now.

Travis fails because scala 2.10.x compilation does not resolve `java.nio.Files` introduced in java 7.

**Comment by eed3si9n** [comment]
sbt 0.13 is on JDK 6, and since Giter8 is integrated out the box with `sbt new` I'd like to keep Giter8 on JDK 6 for now.

**Comment by fabriziofortino** [comment]
@eed3si9n I see your point. I've tried to remove the references to `java.nio` using utilities from apache commons and plxus but the compilation still fails

```
[error] (library/compile:compileIncremental) Compilation failed
[error] Total time: 12 s, completed Apr 27, 2017 4:36:12 PM
The command "jdk_switcher use openjdk6 && sbt "++ 2.10.6" "test:compile"" exited with 1.
```

I think the problem is related to the jgit upgrade.

**Comment by xuwei-k** [comment]
> I think the problem is related to the jgit upgrade.

https://github.com/foundweekends/giter8/pull/207

**Comment by fabriziofortino** [comment]
jgit upgrade reverted. Symbolic links are supported in local mode only.

**Pull request merged**
