### PR TITLE
Added fix for auth_fail

### LINKED ISSUE #117: JGit auth fail
Hi

I'm getting the following exception when trying to install the scalatra-sbt
template:

``` sh
$ g8 scalatra/scalatra-sbt
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:138)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:175)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
        at giter8.Apply$class.clone(apply.scala:73)
        at giter8.Giter8.clone(giter8.scala:3)
        at giter8.Apply$class.inspect(apply.scala:33)
        at giter8.Giter8.inspect(giter8.scala:3)
        at giter8.Apply$class.inspect(apply.scala:55)
        at giter8.Giter8.inspect(giter8.scala:3)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:19)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
        at scala.Option.map(Option.scala:133)
        at giter8.Giter8.run(giter8.scala:18)
        at giter8.Giter8.run(giter8.scala:10)
        at giter8.Giter8.run(giter8.scala:3)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:scalatra/scalatra-sbt.g8.git: Auth fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:141)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
        ... 23 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:461)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
        ... 30 more
```

JGit is failing to use ssh to clone the repository, and I guess its because my
key is protected by gpg-agent(which offers normal ssh-agent emulation). I also
tried to use a full URL with no success:

``` sh
$ g8 https://github.com/scalatra/scalatra-sbt.g8.git
scala.MatchError: https://github.com/scalatra/scalatra-sbt (of class java.lang.String)
        at giter8.Apply$class.inspect(apply.scala:24)
        at giter8.Giter8.inspect(giter8.scala:3)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:19)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
        at scala.Option.map(Option.scala:133)
        at giter8.Giter8.run(giter8.scala:18)
        at giter8.Giter8.run(giter8.scala:10)
        at giter8.Giter8.run(giter8.scala:3)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: scala.MatchError: https://github.com/scalatra/scalatra-sbt (of class java.lang.String)
```

Any ideas on how I might work around this?

### LINKED ISSUE #131: Use ssh known_hosts when accessing native git non-github private repo
[Readme claims](https://github.com/n8han/giter8#private-repositories) that "Giter8 will use your ssh key to access private repositories, just like git does.". Problem is that it needs to also use known_hosts file (and config file). Otherwise one gets exceptions like:

```
C:\temp>g8 git@foo.bar.com/template.g8.git
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:138)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:175)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
        at giter8.Apply$class.clone(apply.scala:80)
        at giter8.Giter8.clone(giter8.scala:3)
        at giter8.Apply$class.inspect(apply.scala:40)
        at giter8.Giter8.inspect(giter8.scala:3)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:19)
        at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
        at scala.Option.map(Option.scala:133)
        at giter8.Giter8.run(giter8.scala:18)
        at giter8.Giter8.run(giter8.scala:10)
        at giter8.Giter8.run(giter8.scala:3)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: org.eclipse.jgit.errors.TransportException: git@foo.bar.com/template.g8.git: UnknownHostKey: foo.bar.com.
RSA key fingerprint is 10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:141)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
        ... 21 more
Caused by: com.jcraft.jsch.JSchException: UnknownHostKey: foo.bar.com. RSA
key fingerprint is 10:10:10:10:10:10:10:10:10:10:10:10:10:10:10:10
        at com.jcraft.jsch.Session.checkHost(Session.java:718)
        at com.jcraft.jsch.Session.connect(Session.java:313)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
        ... 28 more
Error during sbt execution: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of fetch command
```

I have the key, private and pub, as well as known_hosts and config file in .ssh directory within my home directory, but giter8 is not using them.

### LINKED ISSUE #163: scala.MatchError when working with private repo
Installed g8 with homebrew, works fine with public repos, but when I make my repo private, it shows the following error message.

```
$ g8 myprivate/repo.g8.git
scala.MatchError: org.eclipse.jgit.transport.CredentialItem$StringType@565f390 (of class org.eclipse.jgit.transport.CredentialItem$StringType)
    at giter8.ConsoleCredentialsProvider$$anonfun$get$1.apply(apply.scala:134)
    at giter8.ConsoleCredentialsProvider$$anonfun$get$1.apply(apply.scala:134)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
    at giter8.ConsoleCredentialsProvider$.get(apply.scala:134)
    at giter8.ConsoleCredentialsProvider$.get(apply.scala:127)
    at org.eclipse.jgit.transport.CredentialsProviderUserInfo.promptPassphrase(CredentialsProviderUserInfo.java:98)
    at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:116)
    at com.jcraft.jsch.Session.connect(Session.java:425)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:248)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:147)
    at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:127)
    at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:113)
    at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1062)
    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:129)
    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:175)
    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:121)
    at giter8.Apply$class.clone(apply.scala:95)
    at giter8.Giter8.clone(giter8.scala:3)
    at giter8.Apply$class.inspect(apply.scala:54)
    at giter8.Giter8.inspect(giter8.scala:3)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:22)
    at giter8.Giter8$$anonfun$2.apply(giter8.scala:18)
    at scala.Option.map(Option.scala:145)
    at giter8.Giter8.run(giter8.scala:18)
    at giter8.Giter8$.main(giter8.scala:92)
    at giter8.Giter8.main(giter8.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at xsbt.boot.PlainApplication.run(PlainApplication.scala:18)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: scala.MatchError: org.eclipse.jgit.transport.CredentialItem$StringType@565f390 (of class org.eclipse.jgit.transport.CredentialItem$StringType)
```

### LINKED ISSUE #326: CLI Won't Generate from Private Remote Repository with ssh config
If you have a config file in ~/$USER_HOME/.ssh - the g8 command line will not work properly.

Expected behavior - it would identify the proper key via the config and use that to login via ssh to GitHub 

Actual behavior - authentication fails and you are asked for username and password - which never work.

The only work around I currently have is to checkout the giter8 template projects locally and then use the file:// url to get to them.  Ideally this should 'just work'.

OS: Mac OS X 10.12.6
Giter8 - 0.9.0 (via brew)

### LINKED ISSUE #546: --branch xyz fails wit 'remote hung up unexpectedly' on ssh:// urls
## steps

No steps required.
sbt 1.5.0.

## problem

`sbt new` fails when using the `--branch` switch on an `ssh://...` protocol g8 template, e.g.:
```zsh
% sbt new ssh://git@github.com/scala/scala-seed.g8.git
>>> -no problem-
% sbt new ssh://git@github.com/scala/scala-seed.g8.git --branch 2.12.x
[...]
ssh://git@github.com/scala/scala-seed.g8.git: remote hung up unexpectedly
```

<details>

<summary>stack trace</summary>

```zsh
% sbt -v new ssh://git@github.com/scala/scala-seed.g8.git --branch 2.12.x
[sbt_options] declare -a sbt_options=()
[process_args] java_version = '15'
[copyRt] java9_rt = '/Users/jasperstein/.sbt/1.0/java9-rt-ext-n_a_15_0_2/rt.jar'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dscala.ext.dirs=/Users/jasperstein/.sbt/1.0/java9-rt-ext-n_a_15_0_2
-jar
/usr/local/Cellar/sbt/1.5.0/libexec/bin/sbt-launch.jar
new
ssh://git@github.com/scala/scala-seed.g8.git
--branch
2.12.x

[info] welcome to sbt 1.5.0 (N/A Java 15.0.2)
[info] loading settings for project global-plugins-build-build-build from metals.sbt ...
[info] loading global plugins from /Users/jasperstein/.sbt/1.0/plugins/project/project/project
[info] loading settings for project global-plugins-build-build from metals.sbt ...
[info] loading global plugins from /Users/jasperstein/.sbt/1.0/plugins/project/project
[success] Generated .bloop/global-plugins-build-build.json
[success] Total time: 0 s, completed 26 apr. 2021 12:30:07
[info] loading settings for project global-plugins-build from build.sbt ...
[info] loading global plugins from /Users/jasperstein/.sbt/1.0/plugins/project
[success] Generated .bloop/global-plugins-build.json
[success] Total time: 0 s, completed 26 apr. 2021 12:30:08
[info] loading global plugins from /Users/jasperstein/.sbt/1.0/plugins
[info] loading project definition from /Users/jasperstein/tmp/project
[info] set current project to tmp (in build file:/Users/jasperstein/tmp/)
[info] set current project to tmp (in build file:/Users/jasperstein/tmp/)

ssh://git@github.com/scala/scala-seed.g8.git: remote hung up unexpectedly
```

</details>

## expectation

The 2.12.x branch of scala-seed.g8 is used to generate a seed project

### PR DESCRIPTION
**Pull request by TonioGela**
I think I found a working fix for the famous `auth fail` problem that occurs with private repositories or in the case of custom configurations like when you have a `~/.ssh/config`

I've tried to keep the philosophy introduced by @steinybot  with [this commit](https://github.com/foundweekends/giter8/commit/8d7cac6e4a4d9634a139ce5f100db9d62d2fc2dd#diff-ec91a1881c7b5ed50e572c7e8b068a18139c8d4e2d69eeccc9f0d7cf5f10c64e) and [the following](https://github.com/foundweekends/giter8/commit/90e597723e84d103d0c2f536bc5dbbc7f35ed7f3#diff-ec91a1881c7b5ed50e572c7e8b068a18139c8d4e2d69eeccc9f0d7cf5f10c64e)

The main idea is that PROBABLY the `JschConfigSessionFactory` that was overridden before cannot read custom ssh configurations, identity files or keys, while the default implementation `SshdSessionFactory` "mina-sshd" by apache seems to be able to.

I spotted the working implementation simply commenting [this line](https://github.com/foundweekends/giter8/blob/develop/cli-git/src/main/scala/GitInteractor.scala#L53) and printing `x` one the next one. Since not using `SshAgentSessionFactory` worked for me and my custom configuration I thought it could have been a good starting point.

To keep the "custom known_host" configurability option I used the input `knownHosts: Option[String]` to override  `getDefaultKnownHostsFiles`.

I'll keep this PR as a draft until a consistent number of people might be able to test it.

In order to test it, the easiest way is to checkout this PR and then
```
sbt publishLocal
cs bootstrap org.foundweekends.giter8:giter8-launcher_2.12:0.13.1-SNAPSHOT --main giter8.LauncherMain -f -o ~/Desktop/g8-test
./g8-test <ssh:// or git@ URL of a repo>
```

If it works it should:
 - close #117 
 - close #163 
 - close #326 
 - close #131

and probably #176 and #548 too

### CODE REVIEW

**Comment by TonioGela** [comment]
@eed3si9n whenever you have time, I'll be glad to know what do you think about it. If it seems okay to you, I'll ask privately to a bunch of people to test it.

**Comment by eed3si9n** [comment]
Generally I support the idea of moving away from JSch. Last two updates were from 2016 and 2018, and the project has been unresponsive to bug reports like https://sourceforge.net/p/jsch/bugs/129/ "JSchException: invalid privatekey", so it totally makes sense for JGit to migrate to Apache MINA implementation instead.

**Comment by TonioGela** [comment]
Okay, fantastic. I'll begin asking some people to check it out to ensure that it works with most configurations. I'll keep you posted.
P.s. ofc with my company's GitLab instance works.
Thanks Eugene

**Comment by TonioGela** [comment]
> Okay, fantastic. I'll begin asking some people to check it out to ensure that it works with most configurations. I'll keep you posted.
> P.s. ofc with my company's GitLab instance works.
> Thanks Eugene

@eed3si9n I had the chance to make just a couple of people test the issue, I haven't had so much traction. What do you suggest? Can we merge it o it's worth waiting?

**Comment by eed3si9n** [comment]
Sorry I just noticed the mention here. I'm happy to move forward if you think it's ready.

**Comment by TonioGela** [comment]
> Sorry I just noticed the mention here. I'm happy to move forward if you think it's ready.

I have to say that I'm using it for a lot of time and had no issue. Truth to be told, not a lot of persons had the chance to test it. I don't sincerely know which is the right thing to do. 
I personally think that it's ready, but that is my opinion, after my personal tests. Probably it's worth merging. Eventual bugs can be addressed later if any. What do you think?

**Review by eed3si9n — APPROVED** [review]

**Pull request merged**
