### PR TITLE
Implement a naive directory config attribute handling #268

### PR DESCRIPTION
**Pull request by lachatak**
Very basic directory config param handling for rendering from git repo with g8 sub-directory templates

Basic implementation since the project in my Intellij is full or errors. Using 2.10.5 scala. It just not compiles properly. Any idea? 
I used console sbt but to verify. It can be more sophisticated and it can have more tests as well..

### CODE REVIEW

**Comment by xuwei-k** [comment]
```
[error] /home/travis/build/foundweekends/giter8/library/src/main/scala/giter8/JgitHelper.scala:21: object file is not a member of package java.nio
[error] import java.nio.file.Paths
[error]                 ^
[error] /home/travis/build/foundweekends/giter8/library/src/main/scala/giter8/JgitHelper.scala:52: not found: value Paths
[error]       case Success(_) => Right(Paths.get(tempdir.getAbsolutePath, config.directory.getOrElse("")).toFile)
[error]                                ^
```

https://travis-ci.org/foundweekends/giter8/builds/204381143#L873

**Comment by eed3si9n** [comment]
Because Giter8 is used as the reference implementation of sbt new, we need to stick with JDK 6 for 2.10 builds.

**Comment by lachatak** [comment]
Hi Guys,
@eed3si9n when do you think it could be merged?
Is the PR and the implementation OK?

Thanks for the feedback,
Krisztian

**Comment by lachatak** [comment]
Any feedabck?
@xuwei-k @eed3si9n

**Comment by eed3si9n** [comment]
Sorry about the late response. Just merged it.

**Pull request merged**
