### PR TITLE
#345 Conditionals for file creation

### LINKED ISSUE #345: Conditionals for file creation
The current version supports conditionals *inside* files, but not *about* files.
That is, I can include or exclude blocks of text depending on the truthiness of a value. I cannot, however, create files only if a certain value is truthy.

This would be hugely helpful in at least one case: the template I'm working on will support multiple deployment options (raw JAR, AWS, debian package...). Each method needs different files to be present in different paths. 

Currently, I can either include everything and ask developers to manually delete what's irrelevant, or include nothing and point them to a repo that contains the right files.

Ideally, they'd just answer a question (`use AWS? [YES/no]`) and everything would be set up.

### PR DESCRIPTION
**Pull request by ihostage**
Fixes #345 
Inspired by https://github.com/lagom/lagom-java.g8/pull/60

### CODE REVIEW

**Comment by eed3si9n** [comment]
@ihostage Thanks. I am actually not familiar with this area of the code, but our latest docs updated in https://github.com/foundweekends/giter8/pull/374 says:

> These could also be used include/exclude files or directories:
> 
> ```bash
> src/main/g8
> ├── \$name__normalize\$
> │   ├── \$if(jvm.truthy)\$jvm\$endif\$
> │   │   └── src
> │   │       └── main
> │   │           └── scala
> │   │               └── \$organization__packaged\$
> │   │                   └── \$name;format="Camel"\$.scala
> ```

Is there a problem with that?
Also does this code change need and update of the doc?

**Comment by ihostage** [comment]
Hi, @eed3si9n 👋 

> Is there a problem with that?

Yep 😞We have a 2 problem now:
1. If I ignore a directory, how written in docs, G8 just skips this directory from the path to file. Nothing to more. All nested directory and files will be created. If I want to ignore a directory, I need to add conditions for all nested directories and pray, that I will see `Skipping existing file: ` on the log because we have a second problem. 😄 
2. Following from the first problem. G8 will crash If I try to ignore file (not a directory) and this file will be templating a first. For example, I have the next easy template:
```
src/main/g8
└── simple_folder
    ├── $if(condition.truthy)$ignored_file$endif$
    └── simple_file.txt
```
Expected result:
```
src/main/g8
└── simple_folder
    └── simple_file.txt
```
Actual result:
```
src/main/g8
└── simple_folder ← it's a file with the content of $if(condition.truthy)$ignored_file$endif$ 😱 
```
How it works:
1. Set `condition=no`
2. Process `src/main/g8/simple_folder/$if(condition.truthy)$ignored_file$endif$`
3. Evaluated path → `src/main/g8/simple_folder`
4. Create file `src/main/g8/simple_folder` with content of `$if(condition.truthy)$ignored_file$endif$`
5. Process `src/main/g8/simple_folder/simple_file.txt`
6. Evaluated path → `src/main/g8/simple_folder/simple_file.txt`
7. Create parent directory `src/main/g8/simple_folder`
8. Crash, because `src/main/g8/simple_folder` is a file, created on point 4.

Test, implemented on this PR, reproduce a two our problem. You can revert my changes of code and run test for seeing current behavior. 😉 

> Also does this code change need and update of the doc?

Nope :smile: On this PR the behavior of G8 that I expected after reading the docs. But you right, I updated PR and added some information about the case of skipping directory from the path.

**Review by eed3si9n — APPROVED** [review]

**Comment by vpavkin** [comment]
For some reason I still see issues described by @ihostage, although I use 0.12.0 :thinking:

**Comment by eugeniyk** [comment]
@vpavkin  `sbt -sbt-version 1.3.12 new ...` looks make conditionals work as expected
@eed3si9n I guess there was a regression in 1.4.x?

**Pull request merged**
