### PR TITLE
SSH agent proxy support

### PR DESCRIPTION
**Pull request by steinybot**
This adds support for proxying to an SSH agent.

This solves the problem reported here https://stackoverflow.com/questions/59541352/auth-fail-when-running-sbt-new

### CODE REVIEW

**Comment by eed3si9n** [comment]
```
[error] /home/travis/build/foundweekends/giter8/cli-git/src/main/scala/SshAgentSessionFactory.scala:31:70: value of is not a member of object java.nio.file.Path
[error]     knownHosts.orElse(KnownHostsPaths.find(path => Files.exists(Path.of(path))))
[error]                                                                      ^
```

**Comment by eed3si9n** [comment]
For some reason I think both Travis-CI org and .com are configured for this organization.

@xuwei-k do you know why?

**Comment by xuwei-k** [comment]
Ah, sorry. I have migrate from `.org` to `.com` some days ago because

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
https://devops.stackexchange.com/a/4305

> as of May 2018, new users and projects (both private and public) should only use travis-ci.com (see official announcement):

 and updated github branch settings now 🙇 

スクリーンショット 2020-04-18 14 52 58

**Comment by eed3si9n** [comment]
I'm actually getting Exception in thread "main" java.util.ServiceConfigurationError: org.eclipse.jgit.transport.SshSessionFactory: 
Provider org.eclipse.jgit.transport.sshd.SshdSessionFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)

after releasing 0.13.0 - https://github.com/foundweekends/giter8/issues/469

Looks like we're not testing this code path?

**Comment by eed3si9n** [comment]
Reproduced in https://github.com/foundweekends/giter8/pull/471

**Comment by eed3si9n** [comment]
Maybe relevant here [[egit-dev] Bug 520927: moving away from JSch](https://www.eclipse.org/lists/egit-dev/msg04556.html) from Nov 2018:

> now that we've managed to get Apache sshd 2.0.0 correctly into Orbit
I've pushed to Gerrit a new implementation of the JGit ssh support
using sshd instead of JSch. I basically followed the steps I had
outlined in bug 520927: https://bugs.eclipse.org/bugs/show_bug.cgi?id=520927
first add tests, then refactor to get rid of unwanted JSch dependencies,
then add the new sshd stuff.

**Comment by eed3si9n** [comment]
https://wiki.eclipse.org/JGit/New_and_Noteworthy/5.8 says:

- include `org.eclipse.jgit.ssh.jsch` in the application if it wants to use `JSch` for SSH connections. If this bundle is present, it will provide the default `SshConnectionFactory`.
- include `org.eclipse.jgit.ssh.apache` in the application if it wants to use [Apache MINA sshd](https://mina.apache.org/sshd-project/) for SSH connections. In an OSGi application set the `SshConnectionFactory` explicitly to a `org.eclipse.jgit.ssh.apache.SshdConnectionFactory` in this case.

**Pull request merged**
